#programs
alias r='ranger'
alias m='ncmpcpp -c ~/.config/ncmpcpp/config'
alias rec="avconv -f alsa -ac 2 -ar 48000 -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -acodec libvorbis -aq 6 $1"
alias snip='avconv -i "${1}" -ss "${2}" -t "${3}" "${4}"'
alias wwwd='w3m www.duckduckgo.com'
alias start-mpd='mpd ~/.config/mpd/mpd.conf'

#shortcut files
alias fc='vim ~/.dotfiles/help/forgettable-commands'
alias vs='vim ~/.dotfiles/help/vim-shortcuts-improved'
alias vv='vim ~/.dotfiles/help/vimvixenkeys.txt'
alias mpvkeys='vim ~/.dotfiles/help/mpvkeys.txt'

#config files
alias cfg-ncmpcpp='vim ~/.config/ncmpcpp/config'
alias cfg-mpd='vim ~/.config/mpd/mpd.conf'
alias cfg-ranger='vim ~/.config/ranger/rc.conf'
alias cfg-ba='vim ~/.bash_aliases'
alias cfg-brc='vim ~/.bashrc'
