" VUNDLE {{{
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and
" initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-markdown'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'Valloric/YouCompleteMe'
Plugin 'junegunn/fzf.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'ajmwagar/vim-deus'
Plugin 'tomasiser/vim-code-dark'
Plugin 'dhruvasagar/vim-table-mode'
Plugin 'jceb/vim-orgmode'
Plugin 'mattn/calendar-vim'
Plugin 'tpope/vim-speeddating'
Plugin 'tpope/vim-repeat'
Plugin 'vim-scripts/utl.vim'
Plugin 'vim-scripts/taglist.vim'
Plugin 'vim-scripts/Tagbar'
Plugin 'vim-scripts/SyntaxRange'
Plugin 'chriskempson/base16-vim'
Plugin 'suan/vim-instant-markdown'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" }}} " Put your non-Plugin stuff after this line
"Airline tweaks {{{
"   let g:airline_left_sep='>'
"   let g:airline_right_sep='<'
    let g:airline_detect_modified             = 1
    let g:airline_detect_paste                = 1
    let g:airline_detect_spell                = 1
    let g:airline_detect_spelllang            = 1
    let g:airline_powerline_fonts             = 1
" }}}
"Ultisnips config {{{
" Trigger configuration. Do not use <tab> if you use
" https://github.com/Valloric/YouCompleteMe.
    let g:UltiSnipsExpandTrigger       = "<tab>"
    let g:UltiSnipsJumpForwardTrigger  = "<tab>"
    let g:UltiSnipsJumpBackwardTrigger = "<c-z>"

" If you want :UltiSnipsEdit to split your window.
    let g:UltiSnipsEditSplit          = "vertical"
    let g:UltisnipsSnippetsDir        = "/home/simon/.vim/customsnips"
    let g:UltiSnipsSnippetDirectories = ["UltiSnips", "/home/simon/.vim/customsnips"]
    cmap USE UltiSnipsEdit
    let g:UltiSnipsUsePythonVersion = 3
" }}}
" YouCompleteMe config {{{
"    let g:ycm_python_binary_path = '/usr/bin/python3'
" }}}
" UltiSnips / YouCompleteMe tab config {{{
function! g:UltiSnips_Complete()
  call UltiSnips#ExpandSnippet()
  if g:ulti_expand_res == 0
    if pumvisible()
      return "\<C-n>"
    else
      call UltiSnips#JumpForwards()
      if g:ulti_jump_forwards_res == 0
        return "\<TAB>"
      endif
    endif
  endif
  return ""
endfunction

function! g:UltiSnips_Reverse()
  call UltiSnips#JumpBackwards()
  if g:ulti_jump_backwards_res == 0
    return "\<C-P>"
  endif

  return ""
endfunction

au InsertEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger     . " <C-R>=g:UltiSnips_Complete()<cr>"
au InsertEnter * exec "inoremap <silent> " .     g:UltiSnipsJumpBackwardTrigger . " <C-R>=g:UltiSnips_Reverse()<cr>"
"}}}
" orgmode config  {{{
    let g:org_heading_shade_leading_stars = 1
    let g:org_indent                      = 1
    let g:org_aggressive_conceal          = 1    |" Should ensure all inline markups are hidden. Experimental!
" }}}
" Vim-markdown config {{{
        let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']
" }}}
" table mode config {{{
    let g:table_mode_corner_corner = '+'
" }}}
" NERDTree config  {{{
    let g:NERDTreeHijackNetrw = 0
" "--------------------------------------------------------------------------}}}
" dragvisuals config {{{
     vmap  <expr>  <LEFT>   DVB_Drag('left')
     vmap  <expr>  <RIGHT>  DVB_Drag('right')
     vmap  <expr>  <DOWN>   DVB_Drag('down')
     vmap  <expr>  <UP>     DVB_Drag('up')
     vmap  <expr>  D        DVB_Duplicate()
" }}}
" listtrans config {{{
    nnoremap  <leader>l   :call ListTrans_toggle_format()<CR>
    vnoremap  <leader>l   :call ListTrans_toggle_format('visual')<CR>
" }}}
"myplugindir {{{
    set rtp+=~/.vim/bundle/uplooker
" }}}
"fzf plugin {{{
    set rtp+=~/.fzfsrc

" Customize fzf colors to match your color scheme
let g:fzf_colors =
 \ { 'fg':      ['fg', 'Normal'],
   \ 'bg':      ['bg', 'Normal'],
   \ 'hl':      ['fg', 'Comment'],
   \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
   \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
   \ 'hl+':     ['fg', 'Statement'],
   \ 'info':    ['fg', 'PreProc'],
   \ 'border':  ['fg', 'Ignore'],
   \ 'prompt':  ['fg', 'Conditional'],
   \ 'pointer': ['fg', 'Exception'],
   \ 'marker':  ['fg', 'Keyword'],
   \ 'spinner': ['fg', 'Label'],
   \ 'header':  ['fg', 'Comment'] }
" }}}
"Basics {{{
    set nocompatible
    set showmode
    set number
    set relativenumber
    syntax on
    set belloff=all
    set cursorline
    set backspace=indent,start,eol
    set wildmenu
    set shortmess+=I
    set virtualedit=block
    cabbrev vhelp   vert help
" }}}
"Set control keys {{{
    " Leader keys
    let mapleader = ","
    let maplocalleader = "\\"
    " Esc mappings for all modes
    inoremap jk <Esc>
    vnoremap jk <Esc>
    cnoremap jk <Esc>
    " Paste issue dodge
    nnoremap <F2> :set invpaste paste?<CR>
    set pastetoggle=<F2>
    nnoremap <F3> :set invnumber<CR>:set invrelativenumber<CR>
    nnoremap <F4> :%s//g<Left><Left>
    map <F6> :setlocal spell! spelllang=en_gb<CR>
    nnoremap <F7> :SAC<CR>
    nnoremap <F8> <C-W>ozt<C-W>s
    nnoremap <F9> O60i-j0
    map <F10> :PLU<CR>
    map <F11> :SHL<CR>
    map <F12> :GLL<CR>
    map <localleader><F12> :SVS<CR>
    set mouse=a
    "Cursor settings
    let &t_SI = "\<Esc>[6 q"
    let &t_SR = "\<Esc>[4 q"
    let &t_EI = "\<Esc>[2 q"
    " Problem keys
    nmap Q  <nop>
    nmap K  <nop>
    cnoremap <C-a> <Home>   |" To allow easy jump to start of command line
    cnoremap <C-e> <End>    |" Already seems to work but wth.
    cnoremap <C-h> <Left>   |" To allow easy editing
    cnoremap <C-l> <Right>  |" As above
    " File navigation
    cmap    BOF    browse oldfiles
    nmap    ##      :b#<CR> |" Jump to last open file
    nmap    <CR>    @@      |" Repeat last macro
    set switchbuf=usetab    |" switch to already open buffer
    set hidden              |" enables hiding (as yet) unsaved buffer
" }}}
" Manage vim's internal files  {{{
" Prevent write-permissions errors
if exists('$SUDO_USER')
    set nobackup
    set nowritebackup
else
    set backupdir=~/.vim/tmp/backup
    set backupdir+=.
endif
" Keep swapfiles out of the way
  " creates a path based on the current buffer's path
if exists('$SUDO_USER')
    set noswapfile
else
    set directory=~/.vim/tmp/swap//
    set directory+=.
endif
" Manage undo files for root and normal user
if exists('$SUDO_USER')
    set noundofile
else
    set undodir=~/.vim/tmp/undo
    set undodir+=.
    set undofile
endif
" Manage viminfo file
if exists('$SUDO_USER')
    set viminfo=
else
    if isdirectory(expand('~/.vim'))
        " name of viminfo file must be last argument
        set viminfo='1000,f1,<500,n~/.config/vim/viminfo
    endif
endif

if !empty(glob('~/.config/vim/viminfo'))
      if !filereadable(expand('~/.config/vim/viminfo'))
            echoerr 'warning: ~/.config/vim/viminfo exists but is not readable'
      endif
endif
"}}}
" vinaigrette  {{{
    nnoremap -  :edit <C-R>=empty(expand('%')) ? '.' : expand('%:p:h')<CR><CR>
"--------------------------------------------------------------------------}}}
"Call fzf {{{
    nnoremap <leader>ff :Files ~/<CR>
    nnoremap <leader>fv :Files ~/.vim/<CR>
" }}}
"NERDtree bindings {{{
    nnoremap <C-n> :NERDTreeToggle<CR>
" }}}
"Source .vimrc {{{
    nnoremap <leader>sv :source ~/.config/vim/vimrc<CR>
    nnoremap <leader>ev :tabe ~/.config/vim/vimrc<CR>
" }}}
"Folding  {{{
    nnoremap <space> za
" }}}
"Tabs / Line breaking/ Format options  {{{
    "Tabs
    set tabstop=4
    set shiftwidth=4
    set expandtab
    set shiftround
    set smarttab    " Enables <BS> for dedenting.
    " Linebreaks and wrapping
    set linebreak
    set textwidth=78
    set wrap
    " Indenting
    set autoindent
    set breakindent
    set breakindentopt=shift:2
    let &showbreak = '⤷ '
    " Format options
    " previous options croql
    set formatoptions=qljn
    set nojoinspaces        |" Don't insert two spaces after J
    " Highlighting
    set highlight+=@:ColorColumn
    set highlight+=N:DiffText
    execute 'highlight link EndOfBuffer ColorColumn'
    " Brackets
    set noshowmatch         |" Don't jump between match brackets. Too annoying.
    " Screenupdating
    set lazyredraw          |" Turns off screenupdating during macro playback
    " Scrolling
    set scrolloff=1
    " Lists
    set list
    set listchars=nbsp:⊘
    set listchars+=tab:‣∙
    set listchars+=extends:⁍
    set listchars+=precedes:⁌
    set listchars+=trail:∘
" }}}
"Colours {{{
    set t_Co=256
    set t_ut=
    set termguicolors
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
"    set background=dark " Setting dark mode
    colorscheme base16-tomorrow-night
"    colorscheme base16-default-dark
    function! ToggleColorCol()
        if !exists('w:ToggledColorCol')
            let w:ToggledColorCol = 0
        endif
        if w:ToggledColorCol == '0'
            set colorcolumn=78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103
            let w:ToggledColorCol = 1
            echom 'colorcolumn enabled'
        else
            set colorcolumn=
            let w:ToggledColorCol = 0
            echom 'colorcolumn off'
        endif
    endfunction
    nnoremap <leader>cc :call ToggleColorCol()<CR>
" }}}
"Searches {{{
    set ignorecase
    set smartcase
    set incsearch
    set showmatch
    set hlsearch
    nnoremap <leader><space> :noh<CR>
" }}}
"Splits at bottom and right {{{
    set splitright  " Moves focus right with split
    set splitbelow  " Moves focus down with split
" }}}
"Easier line traversing {{{
    nnoremap H 0
    nnoremap L $
" }}}
"Marker jumping  {{{
    nnoremap <leader>n /<++><Enter>"_c4l
    nnoremap <leader>p ?<++><Enter>"_c4h
    inoremap <leader>n <Esc>/<++><Enter>"_c4l
    inoremap <leader>p <Esc>?<++><Enter>"_c4h
" }}}
"Compile latex document {{{
    augroup filetype_tex
        autocmd!
        autocmd FileType tex inoremap <F5> <Esc>:!pdflatex<space>%<Enter>a
        autocmd FileType tex nnoremap <F5> :!pdflatex<space>%<Enter>
    augroup END
" }}}
"Templates  {{{
    augroup templates
        autocmd!
        autocmd BufNewFile *.* silent! execute '0r ~/.config/vim/templates/skeleton.'.expand("<afile>:e")
    augroup END
" }}}
"Dictionary test  {{{
    augroup mydictionary
        autocmd!
        autocmd FileType * execute 'setlocal dict+=~/.vim/mydictionaries/'.&filetype.'.txt'
    augroup END
" }}}
"Per filetype abbreviations  {{{
    augroup filetype_vim
        autocmd!
        autocmd FileType vim setlocal foldmethod=marker
        autocmd FileType vim    :iabbrev <buffer> vcm   \|"
    augroup END

    augroup filetype_py
        autocmd!
        autocmd FileType python    :iabbrev <buffer> iff if:<left>
        "mapping to comment out python lines
        autocmd FileType python    nnoremap <buffer> <localleader>cm I#<Esc>
    augroup END

    augroup filetype_js
        autocmd!
        autocmd FileType javascript    :iabbrev <buffer> iff if ()<left>
    augroup END

    augroup filetype_latin
        autocmd!
        autocmd BufNew,BufRead *.ltn setlocal filetype=latin
    augroup END

    augroup filetype_markdown
        autocmd!
        autocmd BufNewFile,BufReadPost *.md set filetype=markdown
    augroup END

    augroup focus
        autocmd BufEnter,FocusGained,VimEnter,WinEnter * let &l:colorcolumn=join(range(79, 150), ',')
        autocmd BufLeave,FocusLost,WinLeave * let &l:colorcolumn=join(range(1, 150), ',')
    augroup END
" }}}
" Handle links  {{{
    " write to urlview
    nnoremap <leader>uv :w<Home>silent <End> !urlview<CR>
    nnoremap <leader>ut :Utl<CR>
" }}}
" Line manipulation  {{{
"Move lines up and down
    nnoremap <leader><Down> ddp
    nnoremap <leader><Up> ddkP
    nnoremap <localleader>j ddp
    nnoremap <localleader>k ddkP
"Insert lines
    nnoremap <leader>o o<Esc>k
    nnoremap <leader>O O<Esc>j
"Delete lines
    nnoremap <leader>do jddk
    nnoremap <leader>dO kdd
" }}}
"Delete trailing whitespace {{{
    nnoremap <leader>w :%s/\s\+$//<CR>
" }}}
"Insert mode text processing {{{
    inoremap II     <Esc>I      |" Move to start of line
    inoremap AA     <Esc>A      |" Move to end of line
" }}}
"Yank to system clipboard {{{
    vnoremap <leader>cp :w !xsel -b<CR><CR>
    nnoremap <leader>cp :.w !xsel -b<CR><CR>
" }}}
"TYPOS {{{
    iabbrev waht what
    iabbrev tehn then
    iabbrev adn and
" }}}
" NETRW tweak {{{
    let g:netrw_liststyle    = 0
    let g:netrw_banner       = 0
    let g:netrw_browse_split = 0
" }}}
" Custom box commenting {{{
function! CommentBlock(comment, ...)
    "If 1 or more opt args, first opt arg is
    let introducer = a:0 >= 1 ? a:1 : "#"

    "If 2 or more opt args, 2nd opt arg is
    let box_char = a:0 >= 2 ? a:2 : "*"

    "If 3 or more opt args, 3rd opt arg is
    let width = a:0 >= 3 ? a:3 : len(a:comment)+5

    " Build the comment box and put the comment inside it...
    return introducer . repeat(box_char,width) . "\<CR>"
    \    . introducer . " " . a:comment . "\<CR>"
    \    . introducer . repeat(box_char,width) . "\<CR>"
endfunction

" Python /Shell comment box insertion map
    imap <silent> cmblk   <C-R>=CommentBlock(input("Enter comment: "),'#','#')<CR>
" }}}
" python {{{
function! MakeNewBuffer()
python3 << endPython

def create_new_buffer(file_name, file_type, contents):
    vim.command('rightbelow vsplit {}'.format(file_name))
    vim.command('normal! ggdG')
    vim.command('setlocal filetype={}'.format(file_type))
    vim.command('setlocal buftype=nowrite')
    vim.command('call append(0, {})'.format(contents))

def make_example_python_buffer():
    contents = ["def example_func():", "    print('I know kung-fu!')"]
    create_new_buffer("Example_buffer", "python", contents)

make_example_python_buffer()

endPython
endfunction
    " command! -nargs=0 MNB execute "normal! a\<C-R>=MakeNewBuffer()\<CR>"
    command! -nargs=0 MNB call MakeNewBuffer()

function! UnshuffleLines() range
python3 << endPython

def get_visual_selection():
    buf = vim.current.buffer
    (starting_line_num, col1) = buf.mark('<')
    (ending_line_num, col2) = buf.mark('>')
    lines = vim.eval('getline({}, {})'.format(starting_line_num, ending_line_num))
    return lines, starting_line_num

visual_selection, start_line = get_visual_selection()
steps = len(visual_selection)//2
new_lines = []
for i in range(steps):
    new_lines.append(visual_selection[i])
    new_lines.append(visual_selection[i+steps])

for i in range(len(new_lines)):
    vim.current.buffer[i+start_line-1] = new_lines[i]

endPython
endfunction
    command! -narg=0 -range USL call UnshuffleLines()
" }}}
" my vimscript functions {{{  
function! RearrangeLines(line1, line2, count) range
    " Rearrange lines from order 1, 3, 5, 2, 4, 6 to 1, 2, 3, 4, 5, 6
    if a:count == -1
        echo "Please visually select lines"
        return
    endif
    let lines = getline(a:line1, a:line2)
    let steps = len(lines)/2
    let new_lines = []
    for i in range(steps)
        call add(new_lines, lines[i])
        call add(new_lines, lines[i + steps])
    endfor
    call setline(a:line1, new_lines)
endfunction
    command! -narg=0 -range RL call RearrangeLines(<line1>, <line2>, <count>)

function! GetLatinVocab(line1) range
    " Wrapper for fetchLatinList.py
    let my_lookup_text = getline(a:line1)
    execute 'read !~/.vim/pythonx/fetchLatinList.py ' . shellescape(my_lookup_text)
    call setpos('.', [0, a:line1, 1, 0])
endfunction
    command! -narg=0 -range GLV call GetLatinVocab(<line1>)

function! GetLatinVocabLines(line1, line2) range
    " Wrapper for fetchLatinList.py
    let my_lookup_lines = getline(a:line1, a:line2)
    let my_lookup_text = join(my_lookup_lines)
    let my_lookup_text = substitute(my_lookup_text, ';', '.', 'g')
    let my_lookup_text = substitute(my_lookup_text, '!', '.', 'g')
    call setpos('.', [0, a:line2, 1, 0])
    execute 'read !~/.vim/pythonx/fetchLatinList.py ' . shellescape(my_lookup_text)
    call setpos('.', [0, a:line1, 1, 0])
endfunction
    command! -narg=0 -range GLL call GetLatinVocabLines(<line1>, <line2>)

function! ShuntLine()
     " Shunt line from cursor onwards down a line
    let [bufno, lineno, colno, offset] = getpos('.')
    let colno = colno - 1
    execute 'normal Do' . string(colno) . 'i p'
endfunction
    command! -narg=0 SHL call ShuntLine()

function! PushLineUp()
    execute 'normal dd'
    call search('^[^-]', 'b')
    execute 'normal p'
endfunction
    command! -narg=0 PLU call PushLineUp()

function! SplitAndAlignOnCol()
    let line_parts = split(getline('.'), '\s\ze\d')
    let start = substitute(line_parts[0], '\s$', '', 'g')
    let number = join(line_parts[1:], '')
    let new_string = printf("%-59s%s", start, number)
    call setline('.', new_string)
endfunction
    command! -narg=0 SAC call SplitAndAlignOnCol()

function! SplitVocabLineIntoSidebar()
    let chosen_match = getline('.')
    let entries = split(chosen_match, ':')
    let headword = entries[0]
    let definitions = split(entries[1], ';')

    35vsplit _Definitions_
    normal! ggdG
    call setline(1, headword . ':')
    call setline(2, definitions)
    execute 'silent 2,$-1s/\n/\r;\r/'
    execute 'silent 2,$s/,/\r/ge'
    call setpos('.', [0, 2, 1, 0])
    let &hlsearch = 0
    execute 'nnoremap <buffer> <F12> :ReEnt<CR>'
    execute 'nnoremap <buffer> <F11> :PrE<CR>'
endfunction
    command! -narg=0 SVS call SplitVocabLineIntoSidebar()

function! ReassembleEntry()
    let headword = getline(1)
    execute 'silent 2,$s/\w\zs$/,/'
    let definitions = getline(2, '$')
    let entry = headword . join(definitions, '')
    let entry = substitute(entry, ',;', ';', 'g')
    let entry = substitute(entry, ';;', ';', 'g')
    let entry = substitute(entry, ':;', ':', 'g')
    let entry = substitute(entry, ',$', '', '')
    let entry = substitute(entry, ';$', '', '')
    execute 'close'
    call setline('.', entry)
    let &hlsearch = 1
endfunction
    command! -narg=0 ReEnt call ReassembleEntry()

function! PromoteEntry()
    let entry = getline('.')
    normal! 2GdG
    call setline(2, entry)
    call ReassembleEntry()
endfunction
    command! -narg=0 PrE call PromoteEntry()
" }}}
" expression mappings {{{
   iabbrev   <expr>   dts   strftime('%a %d-%m-%Y %H:%M')
" }}}
